import { Link } from 'react-router-dom'

export default function Terms() {
  return (
    <div className="min-h-screen bg-slate-900 text-slate-100">
      <div className="max-w-2xl mx-auto px-4 md:px-6 py-12 md:py-16">
        <Link to="/" className="text-sm text-slate-400 hover:text-slate-200 mb-8 inline-block">← Home</Link>

        <h1 className="text-3xl font-bold mb-6">Terms of Use</h1>

        <p className="text-sm text-slate-500 mb-6">Last updated: April 2026</p>

        <div className="space-y-6 text-slate-300 leading-relaxed">
          <p>
            By using ammonitor, you agree to the following terms. If you do not agree, please do not
            use this service.
          </p>

          <h2 className="text-xl font-semibold text-slate-100">Purpose</h2>
          <p>
            ammonitor provides ammonia emission predictions based on the ALFAM2 model and weather
            forecast data. The tool is intended as a decision-support aid for farmers, advisors, and
            researchers.
          </p>

          <h2 className="text-xl font-semibold text-slate-100">No warranty</h2>
          <p>
            ammonitor is provided "as is" without any warranty of any kind, express or implied.
            Predictions are model-based estimates and may deviate from actual field conditions. The
            accuracy of results depends on the quality of the input parameters and the underlying
            weather forecasts.
          </p>

          <h2 className="text-xl font-semibold text-slate-100">Not professional advice</h2>
          <p>
            The results generated by ammonitor do not constitute professional agricultural or
            environmental advice. Users should consult qualified professionals before making
            decisions based on the tool's output. The operator assumes no responsibility for any
            actions taken based on the information provided.
          </p>

          <h2 className="text-xl font-semibold text-slate-100">Availability</h2>
          <p>
            The operator strives to keep ammonitor available but does not guarantee uninterrupted
            access. The service may be modified, suspended, or discontinued at any time without
            notice.
          </p>

          <h2 className="text-xl font-semibold text-slate-100">Open-source license</h2>
          <p>
            The ammonitor source code is licensed under the{' '}
            <a href="https://www.gnu.org/licenses/agpl-3.0.en.html" target="_blank" rel="noopener noreferrer" className="underline hover:text-slate-100">
              GNU Affero General Public License v3.0 (AGPL-3.0)
            </a>. By using this service, you acknowledge that any network use of the software
            entitles you to receive a copy of the source code under the terms of the AGPL-3.0.
            The source code is available on{' '}
            <a href="https://github.com/andreastauboeck/ammonitor" target="_blank" rel="noopener noreferrer" className="underline hover:text-slate-100">
              GitHub
            </a>.
          </p>

          <h2 className="text-xl font-semibold text-slate-100">Third-party services and data</h2>
          <p>
            ammonitor uses data and services from third parties:
          </p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>
              <span className="font-semibold text-slate-100">ALFAM2 model</span> — Emission predictions are based on the ALFAM2 model (Hafner et al.). See{' '}
              <a href="https://projects.au.dk/alfam" target="_blank" rel="noopener noreferrer" className="underline hover:text-slate-100">ALFAM2 project</a>.
            </li>
            <li>
              <span className="font-semibold text-slate-100">Open-Meteo</span> — Weather forecasts provided under{' '}
              <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer" className="underline hover:text-slate-100">CC BY 4.0</a>.
            </li>
            <li>
              <span className="font-semibold text-slate-100">Nominatim / OpenStreetMap</span> — Geocoding and map data &copy; OpenStreetMap contributors, licensed under{' '}
              <a href="https://opendatacommons.org/licenses/odbl/" target="_blank" rel="noopener noreferrer" className="underline hover:text-slate-100">ODbL</a>.
            </li>
          </ul>
          <p>
            The operator does not guarantee the availability or accuracy of these third-party
            services.
          </p>

          <h2 className="text-xl font-semibold text-slate-100">Limitation of liability</h2>
          <p>
            To the maximum extent permitted by applicable law, the operator shall not be liable for
            any direct, indirect, incidental, special, or consequential damages arising from the use
            of or inability to use ammonitor, including but not limited to loss of profits, data, or
            crops.
          </p>

          <h2 className="text-xl font-semibold text-slate-100">Changes to these terms</h2>
          <p>
            These terms may be updated from time to time. Continued use of ammonitor after changes
            constitutes acceptance of the revised terms. The current version is always available at
            this page.
          </p>

          <h2 className="text-xl font-semibold text-slate-100">Contact</h2>
          <p>
            Andreas Tauböck<br />
            Frühstorf 13, 4341 Arbing, Austria<br />
            E-mail: <a href="mailto:9v6uqtoy@anonaddy.me" className="underline hover:text-slate-100">9v6uqtoy@anonaddy.me</a>
          </p>
        </div>
      </div>
    </div>
  )
}
